---
- name: First play
  hosts: all
  vars:
    myname: john
    greeting: Good morning
  tasks:
    - name: Say hello task
      debug:
        msg: "{{ greeting }} to {{ myname}} from Ansible Tower"
      tags:
      - prod

