---
- name: First play
  hosts: all
  vars:
    myname: john
    greeting: peace to you
  tasks:
    - name: Say hello task
      debug:
        msg: "{{ greeting }} Hallo world to {{ myname}} from Ansible"

