- name: Launch a Job Template on tower using the REST API via Personal Access Token
  hosts: localhost
  gather_facts: false
  vars:
    tower_host: tower.lab.example.com
    tower_job: Demo%20Job%20Template
    tower_user: admin
    tower_pass: redhat
  tasks:
    - name: Get personal access token
      uri: 
        url: "https://{{ tower_host }}/api/v2/users/1/personal_tokens/"
        method: POST
        validate_certs: false
        return_content: true
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: 201
      register: response

    - name: Show the return output
      debug:
        var: response
        verbosity: 1
        
    - name: Trigger the Demo Job Template on tower using REST
      uri:
        url: https://{{ tower_host }}/api/v2/job_templates/{{ tower_job }}/launch/
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: yes
        status_code: 201
        headers:
          Authorization: "Bearer {{ response['json']['token'] }}"
          Content-Type: "application/json"
      register: output

    - name: Show the return output
      debug:
        var: output
        verbosity: 1
