- name: Launch a Job Template on tower using the REST API
  hosts: localhost
  vars:
    tower_host: tower.lab.example.com
    tower_job: Demo%20Job%20Template
    tower_user: admin
    tower_pass: redhat
  tasks:
    - name: Trigger the Demo Job Template on tower using REST
      uri:
        url: https://{{ tower_host }}/api/v2/job_templates/{{ tower_job }}/launch/
        method: POST
        validate_certs: no
        return_content: yes
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: 201

