# Use firefox to browse the API to api/v2/users
# Use the OPTIONS action button to get info on the endpoint
# - Scroll through and you will see the POST action and the 
#   list of fields it accepts and whether it is required or not

- name: Delete a user using the REST API
  hosts: localhost
  gather_facts: false
  vars:
    tower_host: tower.lab.example.com
    tower_user: admin
    tower_pass: redhat
    user_to_delete: "zzuser"
  tasks:
    - name: DELETE a tower user via REST API
      uri:
        url: "{{  'https://' +  tower_host +  '/api/v2/users/' + user_to_delete + '/' | urlencode }}"
        # https://tower.lab.example.com/api/v2/users/zzuser/
        method: DELETE
        validate_certs: no
        return_content: yes
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: 204
      register: output
    - name: Show the return output
      debug:
        var: output
        verbosity: 1
