# Use firefox to browse the API to api/v2/users
# Use the OPTIONS action button to get info on the endpoint
# - Scroll through and you will see the POST action and the 
#   list of fields it accepts and whether it is required or not

- name: View a user using the REST API
  hosts: localhost
  gather_facts: false
  vars:
    tower_host: tower.lab.example.com
    tower_user: admin
    tower_pass: redhat
    user_to_view: "zzuser"
  tasks:
    - name: View a tower user via REST API
      uri:
        url: "{{  'https://' +  tower_host +  '/api/v2/users/' + user_to_view + '/' | urlencode }}"
        # https://tower.lab.example.com/api/v2/users/zzuser/
        method: GET
        validate_certs: no
        return_content: yes
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: 200
      register: output
    - name: Show the return output
      debug:
        var: output
        verbosity: 1
    - name: Save the json output to a file converting to yaml format
      copy:
        content: "{{ output.json | to_nice_yaml }}"
        dest: api-output.yaml
