- name: Play that uses a fact and depends on fact caching
  gather_facts: no
  hosts: all
  tasks:
    - debug:
        msg: The ip address is {{ ansible_facts.default_ipv4.address }} 
    - debug:
        msg: The ip address using old fact {{ ansible_default_ipv4.address }}
